export const WORKFLOW_FETCH_TIMEOUT_MS = 60 * 1000;
export const WORKFLOW_JOB_STEPS_RETRY_MS = 5000;
export const WORKFLOW_JOB_STEPS_SERVER_ERROR_RETRY_MAX = 3;
export const WORKFLOW_JOB_STEPS_SERVER_ERROR_RETRY_MS = 500;
