name: action-test
on:
  workflow_dispatch:
    inputs:
      distinct_id:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID.
        run: echo ${{ inputs.distinct_id }}
