name: action-test
on:
  workflow_dispatch:
    inputs:
      cake: # Test for input passthrough.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo input passthrough
        run: echo ${{ github.event.inputs.cake }}
