name: action-test
# on:
#   workflow_dispatch:
#     inputs:
#       distinct_id:
#         required: true
#       cake: # Test for input passthrough.
#         required: true

on:
  workflow_dispatch:
    inputs:
      distinct_id:
        required: true
      cake: # Test for input passthrough.
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: echo input passthrough
        run: echo ${{ github.event.inputs.cake }}
