name: "Trivy Scan"

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  security-scan:
    name: "Security Scans"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner - Human readable output
        uses: aquasecurity/trivy-action@0.18.0
        continue-on-error: true
        with:
          scan-type: "fs"
          scan-ref: '.'
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          timeout: 10m
      - name: Run Trivy vulnerability scanner - machine readable output
        uses: aquasecurity/trivy-action@0.18.0
        continue-on-error: true
        with:
          scan-type: "fs"
          scan-ref: '.'
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          output: 'trivy-results.sarif'
          timeout: 10m
      - name: Upload Trivy report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: trivy_report
          path: trivy-results.sarif

  
