name: "Code Checks"

on:
  workflow_dispatch:

jobs:
  security-scan:
    name: "Security Scans"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Trivy vulnerability scanner - Human readable output
        uses: aquasecurity/trivy-action@0.18.0
        continue-on-error: true
        with:
          scan-type: "config"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          timeout: 10m
      
        

  
