name: Build
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
      - run: pnpm i
      - name: build
        run: pnpm run build:types
      - name: test
        id: test
        if: ${{ always() }}
        run: pnpm run test
      - name: lint
        if: ${{ always() }}
        run: pnpm run lint --max-warnings=0
      - name: style
        if: ${{ always() }}
        run: pnpm run format:check
  codecov: # Send only a single coverage report per run
    needs: [build]
    timeout-minutes: 15
    env:
      CI: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4
      - run: pnpm i
      - name: test
        run: pnpm run test:coverage
      - name: codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
